version: "3"
services:
  ufo:
    build:
      context: .
    ports:
      - "8888:8888"
    networks:
      - internal
    volumes:
      - .:/var/www/html/
      - ./nginx-server.conf:/etc/nginx/conf.d/nginx-server.conf
      - ./logs/nginx:/var/log/nginx/

networks:
  internal:
    driver: bridge